services:
  marzneshin_ip_limit:
    image: ghcr.io/jenaze/marzneshiniplimit:latest
    restart: always
    environment:
      PORT: 6284
    network_mode: host
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    volumes:
      - /opt/marzneshiniplimit/config.json:/marzneshiniplimitcode/config.json
      - /opt/marzneshiniplimit/logs:/marzneshiniplimitcode/logs
    healthcheck:
      test: ["CMD", "python", "/marzneshiniplimitcode/health_check.py"]
      interval: 30s
      timeout: 10s
      retries: 3
